language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
  - develop
notifications:
  email:
    recipients:
    - architect@gmail.com
services:
- mysql
before_install:
- mysql -e 'CREATE DATABASE IF NOT EXISTS bd;'
script:
- mvn verify
- mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify
- mvn sonar:sonar -Dsonar.organization=brunoml1991-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR
